-- Enable UUID extension (usually enabled by default in Supabase, but good practice)
create extension if not exists "uuid-ossp";

-- 0. Create profiles table (Shadow table for auth.users)
-- This allows us to add custom application data and reference users easily in the public schema
create table public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  email text,
  full_name text,
  avatar_url text,
  updated_at timestamptz default now()
);

-- Enable RLS for profiles
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone"
  on public.profiles for select
  using (true);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url'
  );
  return new;
end;
$$ language plpgsql SECURITY DEFINER;

-- Trigger to call the function on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 1. Create accounts table
create table public.accounts (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) on delete cascade not null,
  name text not null,
  category text not null,
  type text not null check (type in ('asset', 'liability')),
  currency text not null check (currency in ('TWD', 'USD', 'JPY')),
  sort_order integer default 0,
  is_archived boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Enable Row Level Security (RLS)
alter table public.accounts enable row level security;

-- Create policies for accounts
create policy "Users can view their own accounts"
  on public.accounts for select
  using (auth.uid() = user_id);

create policy "Users can insert their own accounts"
  on public.accounts for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own accounts"
  on public.accounts for update
  using (auth.uid() = user_id);

create policy "Users can delete their own accounts"
  on public.accounts for delete
  using (auth.uid() = user_id);

-- 2. Create monthly_records table
create table public.monthly_records (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null, -- redundant but good for performance/rls
  account_id uuid references public.accounts(id) on delete cascade not null,
  month text not null, -- format: YYYY-MM
  amount numeric not null default 0,
  updated_at timestamptz default now(),
  
  -- Ensure one record per account per month
  unique(account_id, month)
);

-- Enable Row Level Security (RLS)
alter table public.monthly_records enable row level security;

-- Create policies for monthly_records
create policy "Users can view their own records"
  on public.monthly_records for select
  using (auth.uid() = user_id);

create policy "Users can insert their own records"
  on public.monthly_records for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own records"
  on public.monthly_records for update
  using (auth.uid() = user_id);

create policy "Users can delete their own records"
  on public.monthly_records for delete
  using (auth.uid() = user_id);

-- 3. Function to automatically update updated_at timestamp
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Trigger for accounts
create trigger on_accounts_updated
  before update on public.accounts
  for each row execute procedure public.handle_updated_at();

-- Trigger for monthly_records
create trigger on_monthly_records_updated
  before update on public.monthly_records
  for each row execute procedure public.handle_updated_at();

-- 4. (Optional) Indexes for performance
create index idx_accounts_user_id on public.accounts(user_id);
create index idx_monthly_records_user_id on public.monthly_records(user_id);
create index idx_monthly_records_month on public.monthly_records(month);
